// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestCaseRunningStageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCaseRunningStage() {
    driver.get("http://localhost:10008/");
    driver.manage().window().setSize(new Dimension(1303, 962));
    driver.findElement(By.cssSelector(".w3-black:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".w3-opacity")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".w3-twothird:nth-child(1) .w3-button")).click();
    driver.findElement(By.cssSelector(".w3-black:nth-child(3)")).click();
    driver.findElement(By.cssSelector("a:nth-child(2) > .w3-button")).click();
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.linkText("Test WebServer Path")).click();
    driver.findElement(By.linkText("do external links work?")).click();
    driver.findElement(By.linkText("do simple relative internal links work?")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do simple absolute links work")).click();
    driver.findElement(By.linkText("do general relative links work")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do general absolute links work")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do TXT files work")).click();
  }
}
